// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovnsb

const AdvertisedMACBindingTable = "Advertised_MAC_Binding"

// AdvertisedMACBinding defines an object in Advertised_MAC_Binding table
type AdvertisedMACBinding struct {
	UUID        string            `ovsdb:"_uuid"`
	Datapath    string            `ovsdb:"datapath"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	IP          string            `ovsdb:"ip"`
	LogicalPort string            `ovsdb:"logical_port"`
	MAC         string            `ovsdb:"mac"`
}
