// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovnsb

const DHCPOptionsTable = "DHCP_Options"

type (
	DHCPOptionsType = string
)

var (
	DHCPOptionsTypeBool         DHCPOptionsType = "bool"
	DHCPOptionsTypeDomains      DHCPOptionsType = "domains"
	DHCPOptionsTypeHostID       DHCPOptionsType = "host_id"
	DHCPOptionsTypeIpv4         DHCPOptionsType = "ipv4"
	DHCPOptionsTypeStaticRoutes DHCPOptionsType = "static_routes"
	DHCPOptionsTypeStr          DHCPOptionsType = "str"
	DHCPOptionsTypeUint16       DHCPOptionsType = "uint16"
	DHCPOptionsTypeUint32       DHCPOptionsType = "uint32"
	DHCPOptionsTypeUint8        DHCPOptionsType = "uint8"
)

// DHCPOptions defines an object in DHCP_Options table
type DHCPOptions struct {
	UUID string          `ovsdb:"_uuid"`
	Code int             `ovsdb:"code"`
	Name string          `ovsdb:"name"`
	Type DHCPOptionsType `ovsdb:"type"`
}
