// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovnsb

const LearnedRouteTable = "Learned_Route"

// LearnedRoute defines an object in Learned_Route table
type LearnedRoute struct {
	UUID        string            `ovsdb:"_uuid"`
	Datapath    string            `ovsdb:"datapath"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	IPPrefix    string            `ovsdb:"ip_prefix"`
	LogicalPort string            `ovsdb:"logical_port"`
	Nexthop     string            `ovsdb:"nexthop"`
}
