// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovnsb

const MeterTable = "Meter"

type (
	MeterUnit = string
)

var (
	MeterUnitKbps  MeterUnit = "kbps"
	MeterUnitPktps MeterUnit = "pktps"
)

// Meter defines an object in Meter table
type Meter struct {
	UUID  string    `ovsdb:"_uuid"`
	Bands []string  `ovsdb:"bands"`
	Name  string    `ovsdb:"name"`
	Unit  MeterUnit `ovsdb:"unit"`
}
