// Wrapper to run the modernize analyzer with ability to skip generated files
package main

import (
	"go/ast"
	"path/filepath"
	"reflect"
	"regexp"
	"slices"
	"strings"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/multichecker"
	"golang.org/x/tools/go/analysis/passes/modernize"
)

var (
	commentRegex = regexp.MustCompile(`^Code generated by .* DO NOT EDIT\.$`)

	Analyzer = &analysis.Analyzer{
		Name:             "skipgenerated",
		Doc:              "filters out the generated files from analysis",
		Run:              run,
		RunDespiteErrors: true,
		ResultType:       reflect.TypeFor[[]*ast.File](),
	}
)

func run(pass *analysis.Pass) (any, error) {
	files := make([]*ast.File, 0, len(pass.Files))
LOOP_FILES:
	for f := range slices.Values(pass.Files) {
		filename := filepath.Base(pass.Fset.Position(f.Pos()).Filename)
		if strings.HasPrefix(filename, "zz_generated.") ||
			strings.HasSuffix(filename, "_generated.go") {
			continue
		}

		for comment := range slices.Values(f.Comments) {
			if commentRegex.MatchString(comment.Text()) {
				continue LOOP_FILES
			}
		}
		files = append(files, f)
	}
	return files, nil
}

func main() {
	multichecker.Main(slices.Insert(modernize.Suite, 0, Analyzer)...)
}
