/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	applyconfigurationkubeovnv1 "github.com/kubeovn/kube-ovn/pkg/client/applyconfiguration/kubeovn/v1"
	scheme "github.com/kubeovn/kube-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RouterLBRulesGetter has a method to return a RouterLBRuleInterface.
// A group's client should implement this interface.
type RouterLBRulesGetter interface {
	RouterLBRules() RouterLBRuleInterface
}

// RouterLBRuleInterface has methods to work with RouterLBRule resources.
type RouterLBRuleInterface interface {
	Create(ctx context.Context, routerLBRule *kubeovnv1.RouterLBRule, opts metav1.CreateOptions) (*kubeovnv1.RouterLBRule, error)
	Update(ctx context.Context, routerLBRule *kubeovnv1.RouterLBRule, opts metav1.UpdateOptions) (*kubeovnv1.RouterLBRule, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, routerLBRule *kubeovnv1.RouterLBRule, opts metav1.UpdateOptions) (*kubeovnv1.RouterLBRule, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kubeovnv1.RouterLBRule, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kubeovnv1.RouterLBRuleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kubeovnv1.RouterLBRule, err error)
	Apply(ctx context.Context, routerLBRule *applyconfigurationkubeovnv1.RouterLBRuleApplyConfiguration, opts metav1.ApplyOptions) (result *kubeovnv1.RouterLBRule, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, routerLBRule *applyconfigurationkubeovnv1.RouterLBRuleApplyConfiguration, opts metav1.ApplyOptions) (result *kubeovnv1.RouterLBRule, err error)
	RouterLBRuleExpansion
}

// routerLBRules implements RouterLBRuleInterface
type routerLBRules struct {
	*gentype.ClientWithListAndApply[*kubeovnv1.RouterLBRule, *kubeovnv1.RouterLBRuleList, *applyconfigurationkubeovnv1.RouterLBRuleApplyConfiguration]
}

// newRouterLBRules returns a RouterLBRules
func newRouterLBRules(c *KubeovnV1Client) *routerLBRules {
	return &routerLBRules{
		gentype.NewClientWithListAndApply[*kubeovnv1.RouterLBRule, *kubeovnv1.RouterLBRuleList, *applyconfigurationkubeovnv1.RouterLBRuleApplyConfiguration](
			"router-lb-rules",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kubeovnv1.RouterLBRule { return &kubeovnv1.RouterLBRule{} },
			func() *kubeovnv1.RouterLBRuleList { return &kubeovnv1.RouterLBRuleList{} },
		),
	}
}
