/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/alauda/kube-ovn/pkg/apis/kubeovn/v1"
	scheme "github.com/alauda/kube-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VpcsGetter has a method to return a VpcInterface.
// A group's client should implement this interface.
type VpcsGetter interface {
	Vpcs() VpcInterface
}

// VpcInterface has methods to work with Vpc resources.
type VpcInterface interface {
	Create(*v1.Vpc) (*v1.Vpc, error)
	Update(*v1.Vpc) (*v1.Vpc, error)
	UpdateStatus(*v1.Vpc) (*v1.Vpc, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Vpc, error)
	List(opts metav1.ListOptions) (*v1.VpcList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Vpc, err error)
	VpcExpansion
}

// vpcs implements VpcInterface
type vpcs struct {
	client rest.Interface
}

// newVpcs returns a Vpcs
func newVpcs(c *KubeovnV1Client) *vpcs {
	return &vpcs{
		client: c.RESTClient(),
	}
}

// Get takes name of the vpc, and returns the corresponding vpc object, and an error if there is any.
func (c *vpcs) Get(name string, options metav1.GetOptions) (result *v1.Vpc, err error) {
	result = &v1.Vpc{}
	err = c.client.Get().
		Resource("vpcs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Vpcs that match those selectors.
func (c *vpcs) List(opts metav1.ListOptions) (result *v1.VpcList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.VpcList{}
	err = c.client.Get().
		Resource("vpcs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vpcs.
func (c *vpcs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("vpcs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a vpc and creates it.  Returns the server's representation of the vpc, and an error, if there is any.
func (c *vpcs) Create(vpc *v1.Vpc) (result *v1.Vpc, err error) {
	result = &v1.Vpc{}
	err = c.client.Post().
		Resource("vpcs").
		Body(vpc).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vpc and updates it. Returns the server's representation of the vpc, and an error, if there is any.
func (c *vpcs) Update(vpc *v1.Vpc) (result *v1.Vpc, err error) {
	result = &v1.Vpc{}
	err = c.client.Put().
		Resource("vpcs").
		Name(vpc.Name).
		Body(vpc).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *vpcs) UpdateStatus(vpc *v1.Vpc) (result *v1.Vpc, err error) {
	result = &v1.Vpc{}
	err = c.client.Put().
		Resource("vpcs").
		Name(vpc.Name).
		SubResource("status").
		Body(vpc).
		Do().
		Into(result)
	return
}

// Delete takes name of the vpc and deletes it. Returns an error if one occurs.
func (c *vpcs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("vpcs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vpcs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("vpcs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vpc.
func (c *vpcs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Vpc, err error) {
	result = &v1.Vpc{}
	err = c.client.Patch(pt).
		Resource("vpcs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
