/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	applyconfigurationkubeovnv1 "github.com/kubeovn/kube-ovn/pkg/client/applyconfiguration/kubeovn/v1"
	scheme "github.com/kubeovn/kube-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VpcWireGuardsGetter has a method to return a VpcWireGuardInterface.
// A group's client should implement this interface.
type VpcWireGuardsGetter interface {
	VpcWireGuards() VpcWireGuardInterface
}

// VpcWireGuardInterface has methods to work with VpcWireGuard resources.
type VpcWireGuardInterface interface {
	Create(ctx context.Context, vpcWireGuard *kubeovnv1.VpcWireGuard, opts metav1.CreateOptions) (*kubeovnv1.VpcWireGuard, error)
	Update(ctx context.Context, vpcWireGuard *kubeovnv1.VpcWireGuard, opts metav1.UpdateOptions) (*kubeovnv1.VpcWireGuard, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vpcWireGuard *kubeovnv1.VpcWireGuard, opts metav1.UpdateOptions) (*kubeovnv1.VpcWireGuard, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kubeovnv1.VpcWireGuard, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kubeovnv1.VpcWireGuardList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kubeovnv1.VpcWireGuard, err error)
	Apply(ctx context.Context, vpcWireGuard *applyconfigurationkubeovnv1.VpcWireGuardApplyConfiguration, opts metav1.ApplyOptions) (result *kubeovnv1.VpcWireGuard, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, vpcWireGuard *applyconfigurationkubeovnv1.VpcWireGuardApplyConfiguration, opts metav1.ApplyOptions) (result *kubeovnv1.VpcWireGuard, err error)
	VpcWireGuardExpansion
}

// vpcWireGuards implements VpcWireGuardInterface
type vpcWireGuards struct {
	*gentype.ClientWithListAndApply[*kubeovnv1.VpcWireGuard, *kubeovnv1.VpcWireGuardList, *applyconfigurationkubeovnv1.VpcWireGuardApplyConfiguration]
}

// newVpcWireGuards returns a VpcWireGuards
func newVpcWireGuards(c *KubeovnV1Client) *vpcWireGuards {
	return &vpcWireGuards{
		gentype.NewClientWithListAndApply[*kubeovnv1.VpcWireGuard, *kubeovnv1.VpcWireGuardList, *applyconfigurationkubeovnv1.VpcWireGuardApplyConfiguration](
			"vpc-wireguards",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kubeovnv1.VpcWireGuard { return &kubeovnv1.VpcWireGuard{} },
			func() *kubeovnv1.VpcWireGuardList { return &kubeovnv1.VpcWireGuardList{} },
		),
	}
}
