apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubectl-ko-node-agent
  namespace: {{ .Values.namespace }}
  labels:
    app: kubectl-ko-node-agent
    component: diagnostics
spec:
  selector:
    matchLabels:
      app: kubectl-ko-node-agent
  template:
    metadata:
      labels:
        app: kubectl-ko-node-agent
        component: diagnostics
    spec:
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      automountServiceAccountToken: false
      {{- with compact .Values.global.registry.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: agent
          image: {{ .Values.global.registry.address }}/{{ .Values.global.images.kubeovn.repository }}:{{ .Values.global.images.kubeovn.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/kube-ovn/kubectl-ko-node-agent"]
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: host-run-ovn
              mountPath: /var/run/ovn
            - name: host-run-ovs
              mountPath: /var/run/openvswitch
              mountPropagation: HostToContainer
            - name: host-netns
              mountPath: /var/run/netns
              mountPropagation: HostToContainer
            - name: host-etc-ovn
              mountPath: /etc/ovn
            - name: host-logs-ovn
              mountPath: /var/log/ovn
              readOnly: true
            - name: host-logs-ovs
              mountPath: /var/log/openvswitch
              readOnly: true
            - name: host-logs-kube-ovn
              mountPath: /var/log/kube-ovn
              readOnly: true
            - name: host-cni-conf
              mountPath: /etc/cni/net.d
              readOnly: true
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: host-run-ovn
          hostPath:
            path: /run/ovn
            type: DirectoryOrCreate
        - name: host-run-ovs
          hostPath:
            path: /run/openvswitch
            type: DirectoryOrCreate
        - name: host-netns
          hostPath:
            path: /var/run/netns
            type: DirectoryOrCreate
        - name: host-etc-ovn
          hostPath:
            path: {{ .Values.ovsOvn.ovnDirectory }}
            type: DirectoryOrCreate
        - name: host-logs-ovn
          hostPath:
            path: {{ .Values.logging.directory }}/ovn
            type: DirectoryOrCreate
        - name: host-logs-ovs
          hostPath:
            path: {{ .Values.logging.directory }}/openvswitch
            type: DirectoryOrCreate
        - name: host-logs-kube-ovn
          hostPath:
            path: {{ .Values.logging.directory }}/kube-ovn
            type: DirectoryOrCreate
        - name: host-cni-conf
          hostPath:
            path: {{ .Values.cni.configDirectory }}
            type: DirectoryOrCreate
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
