{{- $centralName := include "kubeovn.centralName" . -}}
{{- $serviceName := include "kubeovn.centralNorthdName" . -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $serviceName }}
  namespace: {{ include "kubeovn.centralNamespace" . }}
  {{- with .Values.central.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.central.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: {{ $serviceName }}
      protocol: TCP
      port: 6643
      targetPort: 6643
  type: ClusterIP
  {{- if eq .Values.networking.stack "Dual" }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ $centralName }}
    app.kubernetes.io/part-of: kube-ovn
    ovn-northd-leader: "true"
  sessionAffinity: None
