kind: Service
apiVersion: v1
metadata:
  name: ovn-nb
  namespace: {{ include "kubeovn.centralNamespace" . }}
  {{- with .Values.central.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.central.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: ovn-nb
      protocol: TCP
      port: 6641
      targetPort: 6641
      {{- if and .Values.central.separated.enabled (or (eq .Values.central.separated.service.type "NodePort") (eq .Values.central.separated.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.central.separated.service.nbNodePort }}
      {{- end }}
  type: {{ ternary .Values.central.separated.service.type "ClusterIP" .Values.central.separated.enabled }}
  {{- if eq .Values.networking.stack "Dual" }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  selector:
    app.kubernetes.io/name: ovn-central
    app.kubernetes.io/part-of: kube-ovn
    ovn-nb-leader: "true"
  sessionAffinity: None
