kind: Service
apiVersion: v1
metadata:
  name: ovn-sb
  namespace: {{ include "kubeovn.centralNamespace" . }}
  {{- with .Values.central.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.central.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: ovn-sb
      protocol: TCP
      port: 6642
      targetPort: 6642
      {{- if and .Values.central.hcp.enabled (or (eq .Values.central.hcp.service.type "NodePort") (eq .Values.central.hcp.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.central.hcp.service.sbNodePort }}
      {{- end }}
  type: {{ ternary (.Values.central.hcp.service.type | default "ClusterIP") "ClusterIP" .Values.central.hcp.enabled }}
  {{- if eq .Values.networking.stack "Dual" }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  selector:
    app.kubernetes.io/name: ovn-central
    app.kubernetes.io/part-of: kube-ovn
    ovn-sb-leader: "true"
  sessionAffinity: None
