run:
  timeout: 15m

output:
  sort-results: true

linters:
  enable:
    - gocritic
    - gofumpt
    - goimports
    - misspell
    - predeclared
    - revive
    - unconvert
    - unused
    - errcheck
    - gosec
    - govet
    - perfsprint
    - usestdlibvars
    - loggercheck
    - whitespace
    - errorlint

issues:
  max-same-issues: 0
  exclude-rules:
    - linters:
        - gocritic
      text: "appendAssign"
    - linters:
        - revive
      text: "don't use an underscore in package name" # package name not change
    - linters:
        - revive
      text: "VpcDns should be VpcDNS"  # api param not change
    - linters:
        - revive
      text: "VpcDnsList should be VpcDNSList" # api param not change
    - linters:
        - gosec
      path: _test\.go
    - linters:
        - gosec
      path: test/

linters-settings:
  goimports:
    local-prefixes: github.com/kubeovn/kube-ovn
  gofumpt:
    extra-rules: true
  perfsprint:
    strconcat: false
  errorlint:
    asserts: false

