// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package vtep

const ArpSourcesRemoteTable = "Arp_Sources_Remote"

// ArpSourcesRemote defines an object in Arp_Sources_Remote table
type ArpSourcesRemote struct {
	UUID    string `ovsdb:"_uuid"`
	Locator string `ovsdb:"locator"`
	SrcMAC  string `ovsdb:"src_mac" validate:"max=9223372036854775806"`
}
