// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package vtep

const LogicalBindingStatsTable = "Logical_Binding_Stats"

// LogicalBindingStats defines an object in Logical_Binding_Stats table
type LogicalBindingStats struct {
	UUID             string `ovsdb:"_uuid"`
	BytesFromLocal   int    `ovsdb:"bytes_from_local" validate:"max=9223372036854775806"`
	BytesToLocal     int    `ovsdb:"bytes_to_local" validate:"max=9223372036854775806"`
	PacketsFromLocal int    `ovsdb:"packets_from_local" validate:"max=9223372036854775806"`
	PacketsToLocal   int    `ovsdb:"packets_to_local" validate:"max=9223372036854775806"`
}
