// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package vtep

const LogicalRouterTable = "Logical_Router"

// LogicalRouter defines an object in Logical_Router table
type LogicalRouter struct {
	UUID          string            `ovsdb:"_uuid"`
	LrFaultStatus []string          `ovsdb:"LR_fault_status" validate:"dive,max=9223372036854775806"`
	ACLBinding    map[string]string `ovsdb:"acl_binding" validate:"dive,keys,max=9223372036854775806"`
	Description   string            `ovsdb:"description" validate:"max=9223372036854775806"`
	Name          string            `ovsdb:"name" validate:"max=9223372036854775806"`
	OtherConfig   map[string]string `ovsdb:"other_config" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	StaticRoutes  map[string]string `ovsdb:"static_routes" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	SwitchBinding map[string]string `ovsdb:"switch_binding" validate:"dive,keys,max=9223372036854775806"`
}
