// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package vtep

const PhysicalSwitchTable = "Physical_Switch"

// PhysicalSwitch defines an object in Physical_Switch table
type PhysicalSwitch struct {
	UUID              string            `ovsdb:"_uuid"`
	Description       string            `ovsdb:"description" validate:"max=9223372036854775806"`
	ManagementIPs     []string          `ovsdb:"management_ips" validate:"dive,max=9223372036854775806"`
	Name              string            `ovsdb:"name" validate:"max=9223372036854775806"`
	OtherConfig       map[string]string `ovsdb:"other_config" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Ports             []string          `ovsdb:"ports"`
	SwitchFaultStatus []string          `ovsdb:"switch_fault_status" validate:"dive,max=9223372036854775806"`
	TunnelIPs         []string          `ovsdb:"tunnel_ips" validate:"dive,max=9223372036854775806"`
	Tunnels           []string          `ovsdb:"tunnels"`
}
