// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package vtep

const PhysicalPortTable = "Physical_Port"

// PhysicalPort defines an object in Physical_Port table
type PhysicalPort struct {
	UUID            string            `ovsdb:"_uuid"`
	ACLBindings     map[int]string    `ovsdb:"acl_bindings" validate:"dive,keys,min=0,max=4095"`
	Description     string            `ovsdb:"description" validate:"max=9223372036854775806"`
	Name            string            `ovsdb:"name" validate:"max=9223372036854775806"`
	OtherConfig     map[string]string `ovsdb:"other_config" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	PortFaultStatus []string          `ovsdb:"port_fault_status" validate:"dive,max=9223372036854775806"`
	VLANBindings    map[int]string    `ovsdb:"vlan_bindings" validate:"dive,keys,min=0,max=4095"`
	VLANStats       map[int]string    `ovsdb:"vlan_stats" validate:"dive,keys,min=0,max=4095"`
}
