// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package vtep

const UcastMacsRemoteTable = "Ucast_Macs_Remote"

// UcastMacsRemote defines an object in Ucast_Macs_Remote table
type UcastMacsRemote struct {
	UUID          string `ovsdb:"_uuid"`
	MAC           string `ovsdb:"MAC" validate:"max=9223372036854775806"`
	Ipaddr        string `ovsdb:"ipaddr" validate:"max=9223372036854775806"`
	Locator       string `ovsdb:"locator"`
	LogicalSwitch string `ovsdb:"logical_switch"`
}
