# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "centos/7"
NODES = 1
ANSIBLE_VERBOSE = true

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
      v.memory = 1536
      v.cpus = 2
  end

  config.vm.define "k8s-master" do |master|
      master_node_ip = "192.168.55.10"

      master.vm.box = IMAGE_NAME
      master.vm.network "private_network", ip: master_node_ip
      master.vm.hostname = "k8s-master"
      master.vm.provision "ansible" do |ansible|
          ansible.playbook = "kubernetes-setup/master-playbook.yml"
          ansible.verbose = ANSIBLE_VERBOSE
          ansible.extra_vars = {
            kubernetes_version: "v1.14.0",
            master_ip: master_node_ip,
            node_ip: master_node_ip,
            pod_network_cidr: "10.16.0.0/16",
            cluster_service_ip_range: "10.96.0.0/16",
            image_repository: "registry.cn-hangzhou.aliyuncs.com/google_containers",
          }
      end
  end

  (1..NODES).each do |i|
      config.vm.define "node-#{i}" do |node|
          slave_node_ip = "192.168.55.#{i + 10}"

          node.vm.box = IMAGE_NAME
          node.vm.network "private_network", ip: slave_node_ip
          node.vm.hostname = "node-#{i}"
          node.vm.provision "ansible" do |ansible|
              ansible.playbook = "kubernetes-setup/node-playbook.yml"
              ansible.verbose = ANSIBLE_VERBOSE
              ansible.extra_vars = {
                  node_ip: slave_node_ip,
              }
          end
      end
  end

end
