// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/client/clientset/versioned/typed/kubeovn/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRouterLBRules implements RouterLBRuleInterface
type fakeRouterLBRules struct {
	*gentype.FakeClientWithList[*v1.RouterLBRule, *v1.RouterLBRuleList]
	Fake *FakeKubeovnV1
}

func newFakeRouterLBRules(fake *FakeKubeovnV1) kubeovnv1.RouterLBRuleInterface {
	return &fakeRouterLBRules{
		gentype.NewFakeClientWithList[*v1.RouterLBRule, *v1.RouterLBRuleList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("router-lb-rules"),
			v1.SchemeGroupVersion.WithKind("RouterLBRule"),
			func() *v1.RouterLBRule { return &v1.RouterLBRule{} },
			func() *v1.RouterLBRuleList { return &v1.RouterLBRuleList{} },
			func(dst, src *v1.RouterLBRuleList) { dst.ListMeta = src.ListMeta },
			func(list *v1.RouterLBRuleList) []*v1.RouterLBRule { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.RouterLBRuleList, items []*v1.RouterLBRule) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
