{{- if .Values.ovsOvn.upgrade.enabled -}}
{{- $hookName := include "kubeovn.resourceName" (dict "context" . "suffix" "ovs-ovn-upgrade") -}}
{{- $hookRoleName := include "kubeovn.resourceName" (dict "context" . "suffix" "system-ovs-ovn-upgrade") -}}
{{- $ovsOvnName := include "kubeovn.ovsOvnName" . -}}
{{- $centralName := include "kubeovn.centralName" . -}}
{{- $tlsSecretName := include "kubeovn.tlsSecretName" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $hookName }}
  namespace: {{ .Values.namespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.k8s.io/system-only: "true"
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
  name: {{ $hookRoleName }}
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    resourceNames:
      - {{ $ovsOvnName }}
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - {{ $centralName }}
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $hookName }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  name: {{ $hookRoleName }}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ $hookName }}
    namespace: {{ .Values.namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hookName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  completions: 1
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: post-upgrade
        component: job
    spec:
      tolerations:
        - key: ""
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - post-upgrade
                  - key: component
                    operator: In
                    values:
                      - job
      restartPolicy: Never
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: "linux"
      serviceAccountName: {{ $hookName }}
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ $hookName }}
          image: "{{ .Values.global.registry.address}}/{{ .Values.global.images.kubeovn.repository }}:{{ .Values.global.images.kubeovn.tag }}"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - bash
            - -eo
            - pipefail
            - -c
            - |
              touch /var/log/kube-ovn/upgrade-ovs.log
              chmod 640 /var/log/kube-ovn/upgrade-ovs.log
              /kube-ovn/upgrade-ovs.sh 2>&1 | tee -a /var/log/kube-ovn/upgrade-ovs.log
          volumeMounts:
            - mountPath: /var/log/kube-ovn
              name: kube-ovn-log
            - mountPath: /var/run/tls
              name: {{ $tlsSecretName }}
      volumes:
        - name: kube-ovn-log
          hostPath:
            path: {{ .Values.logging.directory }}/kube-ovn
        - name: {{ $tlsSecretName }}
          secret:
            optional: true
            secretName: {{ $tlsSecretName }}
{{- end -}}
