---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ovn-cni
  namespace: {{ .Values.namespace }}
  {{- with .Values.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}