// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovnnb

const NetworkFunctionHealthCheckTable = "Network_Function_Health_Check"

// NetworkFunctionHealthCheck defines an object in Network_Function_Health_Check table
type NetworkFunctionHealthCheck struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	Name        string            `ovsdb:"name"`
	Options     map[string]string `ovsdb:"options"`
}
