// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovnnb

const SamplingAppTable = "Sampling_App"

type (
	SamplingAppType = string
)

const (
	SamplingAppTypeDrop   SamplingAppType = "drop"
	SamplingAppTypeACLNew SamplingAppType = "acl-new"
	SamplingAppTypeACLEst SamplingAppType = "acl-est"
)

// SamplingApp defines an object in Sampling_App table
type SamplingApp struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	ID          int               `ovsdb:"id" validate:"min=1,max=255"`
	Type        SamplingAppType   `ovsdb:"type" validate:"oneof='drop' 'acl-new' 'acl-est'"`
}
