// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovnnb

const SampleTable = "Sample"

// Sample defines an object in Sample table
type Sample struct {
	UUID       string   `ovsdb:"_uuid"`
	Collectors []string `ovsdb:"collectors"`
	Metadata   int      `ovsdb:"metadata"`
}
