/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BFDPortStatusApplyConfiguration represents a declarative configuration of the BFDPortStatus type for use
// with apply.
type BFDPortStatusApplyConfiguration struct {
	Name  *string  `json:"name,omitempty"`
	IP    *string  `json:"ip,omitempty"`
	Nodes []string `json:"nodes,omitempty"`
}

// BFDPortStatusApplyConfiguration constructs a declarative configuration of the BFDPortStatus type for use with
// apply.
func BFDPortStatus() *BFDPortStatusApplyConfiguration {
	return &BFDPortStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BFDPortStatusApplyConfiguration) WithName(value string) *BFDPortStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *BFDPortStatusApplyConfiguration) WithIP(value string) *BFDPortStatusApplyConfiguration {
	b.IP = &value
	return b
}

// WithNodes adds the given value to the Nodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nodes field.
func (b *BFDPortStatusApplyConfiguration) WithNodes(values ...string) *BFDPortStatusApplyConfiguration {
	for i := range values {
		b.Nodes = append(b.Nodes, values[i])
	}
	return b
}
