/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BFDPortChassisStatusApplyConfiguration represents a declarative configuration of the BFDPortChassisStatus type for use
// with apply.
type BFDPortChassisStatusApplyConfiguration struct {
	// Node is the Kubernetes node name for this chassis
	Node *string `json:"node,omitempty"`
	// Chassis is the OVN chassis name
	Chassis *string `json:"chassis,omitempty"`
	// Priority is the HA chassis priority
	Priority *int `json:"priority,omitempty"`
	// Ready indicates whether the chassis exists and can be used
	Ready *bool `json:"ready,omitempty"`
}

// BFDPortChassisStatusApplyConfiguration constructs a declarative configuration of the BFDPortChassisStatus type for use with
// apply.
func BFDPortChassisStatus() *BFDPortChassisStatusApplyConfiguration {
	return &BFDPortChassisStatusApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *BFDPortChassisStatusApplyConfiguration) WithNode(value string) *BFDPortChassisStatusApplyConfiguration {
	b.Node = &value
	return b
}

// WithChassis sets the Chassis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Chassis field is set to the value of the last call.
func (b *BFDPortChassisStatusApplyConfiguration) WithChassis(value string) *BFDPortChassisStatusApplyConfiguration {
	b.Chassis = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *BFDPortChassisStatusApplyConfiguration) WithPriority(value int) *BFDPortChassisStatusApplyConfiguration {
	b.Priority = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *BFDPortChassisStatusApplyConfiguration) WithReady(value bool) *BFDPortChassisStatusApplyConfiguration {
	b.Ready = &value
	return b
}
