/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DNSNameResolverStatusApplyConfiguration represents a declarative configuration of the DNSNameResolverStatus type for use
// with apply.
//
// DNSNameResolverStatus defines the observed status of DNSNameResolver.
type DNSNameResolverStatusApplyConfiguration struct {
	// resolvedNames contains a list of matching DNS names and their corresponding IP addresses
	// along with their TTL and last DNS lookup times.
	ResolvedNames []DNSNameResolverResolvedNameApplyConfiguration `json:"resolvedNames,omitempty"`
}

// DNSNameResolverStatusApplyConfiguration constructs a declarative configuration of the DNSNameResolverStatus type for use with
// apply.
func DNSNameResolverStatus() *DNSNameResolverStatusApplyConfiguration {
	return &DNSNameResolverStatusApplyConfiguration{}
}

// WithResolvedNames adds the given value to the ResolvedNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResolvedNames field.
func (b *DNSNameResolverStatusApplyConfiguration) WithResolvedNames(values ...*DNSNameResolverResolvedNameApplyConfiguration) *DNSNameResolverStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResolvedNames")
		}
		b.ResolvedNames = append(b.ResolvedNames, *values[i])
	}
	return b
}
