/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
)

// DNSNameResolverSpecApplyConfiguration represents a declarative configuration of the DNSNameResolverSpec type for use
// with apply.
type DNSNameResolverSpecApplyConfiguration struct {
	// name is the DNS name for which the DNS name resolution information will be stored.
	// For a regular DNS name, only the DNS name resolution information of the regular DNS
	// name will be stored. For a wildcard DNS name, the DNS name resolution information
	// of all the DNS names that match the wildcard DNS name will be stored.
	// For a wildcard DNS name, the '*' will match only one label. Additionally, only a single
	// '*' can be used at the beginning of the wildcard DNS name. For example, '*.example.com.'
	// will match 'sub1.example.com.' but won't match 'sub2.sub1.example.com.'
	Name *kubeovnv1.DNSName `json:"name,omitempty"`
}

// DNSNameResolverSpecApplyConfiguration constructs a declarative configuration of the DNSNameResolverSpec type for use with
// apply.
func DNSNameResolverSpec() *DNSNameResolverSpecApplyConfiguration {
	return &DNSNameResolverSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DNSNameResolverSpecApplyConfiguration) WithName(value kubeovnv1.DNSName) *DNSNameResolverSpecApplyConfiguration {
	b.Name = &value
	return b
}
