/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// IPPoolSpecApplyConfiguration represents a declarative configuration of the IPPoolSpec type for use
// with apply.
type IPPoolSpecApplyConfiguration struct {
	Subnet     *string  `json:"subnet,omitempty"`
	Namespaces []string `json:"namespaces,omitempty"`
	IPs        []string `json:"ips,omitempty"`
	// EnableAddressSet to work with policy-based routing and ACL
	EnableAddressSet *bool `json:"enableAddressSet,omitempty"`
}

// IPPoolSpecApplyConfiguration constructs a declarative configuration of the IPPoolSpec type for use with
// apply.
func IPPoolSpec() *IPPoolSpecApplyConfiguration {
	return &IPPoolSpecApplyConfiguration{}
}

// WithSubnet sets the Subnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subnet field is set to the value of the last call.
func (b *IPPoolSpecApplyConfiguration) WithSubnet(value string) *IPPoolSpecApplyConfiguration {
	b.Subnet = &value
	return b
}

// WithNamespaces adds the given value to the Namespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Namespaces field.
func (b *IPPoolSpecApplyConfiguration) WithNamespaces(values ...string) *IPPoolSpecApplyConfiguration {
	for i := range values {
		b.Namespaces = append(b.Namespaces, values[i])
	}
	return b
}

// WithIPs adds the given value to the IPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPs field.
func (b *IPPoolSpecApplyConfiguration) WithIPs(values ...string) *IPPoolSpecApplyConfiguration {
	for i := range values {
		b.IPs = append(b.IPs, values[i])
	}
	return b
}

// WithEnableAddressSet sets the EnableAddressSet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableAddressSet field is set to the value of the last call.
func (b *IPPoolSpecApplyConfiguration) WithEnableAddressSet(value bool) *IPPoolSpecApplyConfiguration {
	b.EnableAddressSet = &value
	return b
}
