/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// IptablesEIPSpecApplyConfiguration represents a declarative configuration of the IptablesEIPSpec type for use
// with apply.
type IptablesEIPSpecApplyConfiguration struct {
	V4ip           *string `json:"v4ip,omitempty"`
	V6ip           *string `json:"v6ip,omitempty"`
	MacAddress     *string `json:"macAddress,omitempty"`
	NatGwDp        *string `json:"natGwDp,omitempty"`
	QoSPolicy      *string `json:"qosPolicy,omitempty"`
	ExternalSubnet *string `json:"externalSubnet,omitempty"`
}

// IptablesEIPSpecApplyConfiguration constructs a declarative configuration of the IptablesEIPSpec type for use with
// apply.
func IptablesEIPSpec() *IptablesEIPSpecApplyConfiguration {
	return &IptablesEIPSpecApplyConfiguration{}
}

// WithV4ip sets the V4ip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V4ip field is set to the value of the last call.
func (b *IptablesEIPSpecApplyConfiguration) WithV4ip(value string) *IptablesEIPSpecApplyConfiguration {
	b.V4ip = &value
	return b
}

// WithV6ip sets the V6ip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V6ip field is set to the value of the last call.
func (b *IptablesEIPSpecApplyConfiguration) WithV6ip(value string) *IptablesEIPSpecApplyConfiguration {
	b.V6ip = &value
	return b
}

// WithMacAddress sets the MacAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MacAddress field is set to the value of the last call.
func (b *IptablesEIPSpecApplyConfiguration) WithMacAddress(value string) *IptablesEIPSpecApplyConfiguration {
	b.MacAddress = &value
	return b
}

// WithNatGwDp sets the NatGwDp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NatGwDp field is set to the value of the last call.
func (b *IptablesEIPSpecApplyConfiguration) WithNatGwDp(value string) *IptablesEIPSpecApplyConfiguration {
	b.NatGwDp = &value
	return b
}

// WithQoSPolicy sets the QoSPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QoSPolicy field is set to the value of the last call.
func (b *IptablesEIPSpecApplyConfiguration) WithQoSPolicy(value string) *IptablesEIPSpecApplyConfiguration {
	b.QoSPolicy = &value
	return b
}

// WithExternalSubnet sets the ExternalSubnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalSubnet field is set to the value of the last call.
func (b *IptablesEIPSpecApplyConfiguration) WithExternalSubnet(value string) *IptablesEIPSpecApplyConfiguration {
	b.ExternalSubnet = &value
	return b
}
