/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// IptablesSnatRuleSpecApplyConfiguration represents a declarative configuration of the IptablesSnatRuleSpec type for use
// with apply.
type IptablesSnatRuleSpecApplyConfiguration struct {
	EIP          *string `json:"eip,omitempty"`
	InternalCIDR *string `json:"internalCIDR,omitempty"`
}

// IptablesSnatRuleSpecApplyConfiguration constructs a declarative configuration of the IptablesSnatRuleSpec type for use with
// apply.
func IptablesSnatRuleSpec() *IptablesSnatRuleSpecApplyConfiguration {
	return &IptablesSnatRuleSpecApplyConfiguration{}
}

// WithEIP sets the EIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EIP field is set to the value of the last call.
func (b *IptablesSnatRuleSpecApplyConfiguration) WithEIP(value string) *IptablesSnatRuleSpecApplyConfiguration {
	b.EIP = &value
	return b
}

// WithInternalCIDR sets the InternalCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InternalCIDR field is set to the value of the last call.
func (b *IptablesSnatRuleSpecApplyConfiguration) WithInternalCIDR(value string) *IptablesSnatRuleSpecApplyConfiguration {
	b.InternalCIDR = &value
	return b
}
