/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
)

// QoSPolicyBandwidthLimitRuleApplyConfiguration represents a declarative configuration of the QoSPolicyBandwidthLimitRule type for use
// with apply.
//
// BandwidthLimitRule describes the rule of a bandwidth limit.
type QoSPolicyBandwidthLimitRuleApplyConfiguration struct {
	// Rule name
	Name *string `json:"name,omitempty"`
	// Interface name
	Interface *string `json:"interface,omitempty"`
	// Maximum rate in Mbps (e.g., 100 or 0.5 for 500Kbps)
	RateMax *string `json:"rateMax,omitempty"`
	// Maximum burst in MB (e.g., 10 or 0.5 for 500KB)
	BurstMax *string `json:"burstMax,omitempty"`
	// Rule priority
	Priority *int `json:"priority,omitempty"`
	// Traffic direction (ingress/egress)
	Direction *kubeovnv1.QoSPolicyRuleDirection `json:"direction,omitempty"`
	// Match type
	MatchType *kubeovnv1.QoSPolicyRuleMatchType `json:"matchType,omitempty"`
	// Match value
	MatchValue *string `json:"matchValue,omitempty"`
}

// QoSPolicyBandwidthLimitRuleApplyConfiguration constructs a declarative configuration of the QoSPolicyBandwidthLimitRule type for use with
// apply.
func QoSPolicyBandwidthLimitRule() *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	return &QoSPolicyBandwidthLimitRuleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *QoSPolicyBandwidthLimitRuleApplyConfiguration) WithName(value string) *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	b.Name = &value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *QoSPolicyBandwidthLimitRuleApplyConfiguration) WithInterface(value string) *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	b.Interface = &value
	return b
}

// WithRateMax sets the RateMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateMax field is set to the value of the last call.
func (b *QoSPolicyBandwidthLimitRuleApplyConfiguration) WithRateMax(value string) *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	b.RateMax = &value
	return b
}

// WithBurstMax sets the BurstMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BurstMax field is set to the value of the last call.
func (b *QoSPolicyBandwidthLimitRuleApplyConfiguration) WithBurstMax(value string) *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	b.BurstMax = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *QoSPolicyBandwidthLimitRuleApplyConfiguration) WithPriority(value int) *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	b.Priority = &value
	return b
}

// WithDirection sets the Direction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direction field is set to the value of the last call.
func (b *QoSPolicyBandwidthLimitRuleApplyConfiguration) WithDirection(value kubeovnv1.QoSPolicyRuleDirection) *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	b.Direction = &value
	return b
}

// WithMatchType sets the MatchType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchType field is set to the value of the last call.
func (b *QoSPolicyBandwidthLimitRuleApplyConfiguration) WithMatchType(value kubeovnv1.QoSPolicyRuleMatchType) *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	b.MatchType = &value
	return b
}

// WithMatchValue sets the MatchValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchValue field is set to the value of the last call.
func (b *QoSPolicyBandwidthLimitRuleApplyConfiguration) WithMatchValue(value string) *QoSPolicyBandwidthLimitRuleApplyConfiguration {
	b.MatchValue = &value
	return b
}
