/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
)

// SecurityGroupRuleApplyConfiguration represents a declarative configuration of the SecurityGroupRule type for use
// with apply.
type SecurityGroupRuleApplyConfiguration struct {
	// IP version (IPv4 or IPv6)
	IPVersion *string `json:"ipVersion,omitempty"`
	// Protocol (tcp, udp, icmp, or all)
	Protocol *kubeovnv1.SgProtocol `json:"protocol,omitempty"`
	// Rule priority (1-16384)
	Priority *int `json:"priority,omitempty"`
	// Type of remote (address, cidr, or securityGroup)
	RemoteType *kubeovnv1.SgRemoteType `json:"remoteType,omitempty"`
	// Remote address or CIDR
	RemoteAddress *string `json:"remoteAddress,omitempty"`
	// Remote security group name
	RemoteSecurityGroup *string `json:"remoteSecurityGroup,omitempty"`
	// Start of port range (1-65535)
	PortRangeMin *int `json:"portRangeMin,omitempty"`
	// End of port range (1-65535)
	PortRangeMax *int `json:"portRangeMax,omitempty"`
	// Local address or CIDR
	LocalAddress *string `json:"localAddress,omitempty"`
	// Start of source port range (1-65535)
	SourcePortRangeMin *int `json:"sourcePortRangeMin,omitempty"`
	// End of source port range (1-65535)
	SourcePortRangeMax *int `json:"sourcePortRangeMax,omitempty"`
	// Policy action (allow, pass or deny)
	Policy *kubeovnv1.SgPolicy `json:"policy,omitempty"`
}

// SecurityGroupRuleApplyConfiguration constructs a declarative configuration of the SecurityGroupRule type for use with
// apply.
func SecurityGroupRule() *SecurityGroupRuleApplyConfiguration {
	return &SecurityGroupRuleApplyConfiguration{}
}

// WithIPVersion sets the IPVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPVersion field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithIPVersion(value string) *SecurityGroupRuleApplyConfiguration {
	b.IPVersion = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithProtocol(value kubeovnv1.SgProtocol) *SecurityGroupRuleApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithPriority(value int) *SecurityGroupRuleApplyConfiguration {
	b.Priority = &value
	return b
}

// WithRemoteType sets the RemoteType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteType field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithRemoteType(value kubeovnv1.SgRemoteType) *SecurityGroupRuleApplyConfiguration {
	b.RemoteType = &value
	return b
}

// WithRemoteAddress sets the RemoteAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteAddress field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithRemoteAddress(value string) *SecurityGroupRuleApplyConfiguration {
	b.RemoteAddress = &value
	return b
}

// WithRemoteSecurityGroup sets the RemoteSecurityGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteSecurityGroup field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithRemoteSecurityGroup(value string) *SecurityGroupRuleApplyConfiguration {
	b.RemoteSecurityGroup = &value
	return b
}

// WithPortRangeMin sets the PortRangeMin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortRangeMin field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithPortRangeMin(value int) *SecurityGroupRuleApplyConfiguration {
	b.PortRangeMin = &value
	return b
}

// WithPortRangeMax sets the PortRangeMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortRangeMax field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithPortRangeMax(value int) *SecurityGroupRuleApplyConfiguration {
	b.PortRangeMax = &value
	return b
}

// WithLocalAddress sets the LocalAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalAddress field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithLocalAddress(value string) *SecurityGroupRuleApplyConfiguration {
	b.LocalAddress = &value
	return b
}

// WithSourcePortRangeMin sets the SourcePortRangeMin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourcePortRangeMin field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithSourcePortRangeMin(value int) *SecurityGroupRuleApplyConfiguration {
	b.SourcePortRangeMin = &value
	return b
}

// WithSourcePortRangeMax sets the SourcePortRangeMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourcePortRangeMax field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithSourcePortRangeMax(value int) *SecurityGroupRuleApplyConfiguration {
	b.SourcePortRangeMax = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *SecurityGroupRuleApplyConfiguration) WithPolicy(value kubeovnv1.SgPolicy) *SecurityGroupRuleApplyConfiguration {
	b.Policy = &value
	return b
}
