/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VipStatusApplyConfiguration represents a declarative configuration of the VipStatus type for use
// with apply.
type VipStatusApplyConfiguration struct {
	// Conditions represents the latest state of the object
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
	Type       *string                       `json:"type,omitempty"`
	V4ip       *string                       `json:"v4ip,omitempty"`
	V6ip       *string                       `json:"v6ip,omitempty"`
	Mac        *string                       `json:"mac,omitempty"`
}

// VipStatusApplyConfiguration constructs a declarative configuration of the VipStatus type for use with
// apply.
func VipStatus() *VipStatusApplyConfiguration {
	return &VipStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *VipStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *VipStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *VipStatusApplyConfiguration) WithType(value string) *VipStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithV4ip sets the V4ip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V4ip field is set to the value of the last call.
func (b *VipStatusApplyConfiguration) WithV4ip(value string) *VipStatusApplyConfiguration {
	b.V4ip = &value
	return b
}

// WithV6ip sets the V6ip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V6ip field is set to the value of the last call.
func (b *VipStatusApplyConfiguration) WithV6ip(value string) *VipStatusApplyConfiguration {
	b.V6ip = &value
	return b
}

// WithMac sets the Mac field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mac field is set to the value of the last call.
func (b *VipStatusApplyConfiguration) WithMac(value string) *VipStatusApplyConfiguration {
	b.Mac = &value
	return b
}
