/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VpcEgressGatewayConntrackLogRateLimitApplyConfiguration represents a declarative configuration of the VpcEgressGatewayConntrackLogRateLimit type for use
// with apply.
//
// VpcEgressGatewayConntrackLogRateLimit limits flow log records per gateway pod.
type VpcEgressGatewayConntrackLogRateLimitApplyConfiguration struct {
	RecordsPerSecond *int32 `json:"recordsPerSecond,omitempty"`
	Burst            *int32 `json:"burst,omitempty"`
}

// VpcEgressGatewayConntrackLogRateLimitApplyConfiguration constructs a declarative configuration of the VpcEgressGatewayConntrackLogRateLimit type for use with
// apply.
func VpcEgressGatewayConntrackLogRateLimit() *VpcEgressGatewayConntrackLogRateLimitApplyConfiguration {
	return &VpcEgressGatewayConntrackLogRateLimitApplyConfiguration{}
}

// WithRecordsPerSecond sets the RecordsPerSecond field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecordsPerSecond field is set to the value of the last call.
func (b *VpcEgressGatewayConntrackLogRateLimitApplyConfiguration) WithRecordsPerSecond(value int32) *VpcEgressGatewayConntrackLogRateLimitApplyConfiguration {
	b.RecordsPerSecond = &value
	return b
}

// WithBurst sets the Burst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Burst field is set to the value of the last call.
func (b *VpcEgressGatewayConntrackLogRateLimitApplyConfiguration) WithBurst(value int32) *VpcEgressGatewayConntrackLogRateLimitApplyConfiguration {
	b.Burst = &value
	return b
}
