/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VpcEndpointStatusApplyConfiguration represents a declarative configuration of the VpcEndpointStatus type for use
// with apply.
type VpcEndpointStatusApplyConfiguration struct {
	// IP in the consumer subnet that applications dial.
	LocalVIP *string `json:"localVIP,omitempty"`
	// Provider transit VIP this endpoint maps to.
	TransitVIP *string `json:"transitVIP,omitempty"`
	// Shared SNAT IP of the consumer VPC on the transit subnet.
	SnatIP *string `json:"snatIP,omitempty"`
	// Indicates whether the endpoint is ready.
	Ready      *bool                         `json:"ready,omitempty"`
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// VpcEndpointStatusApplyConfiguration constructs a declarative configuration of the VpcEndpointStatus type for use with
// apply.
func VpcEndpointStatus() *VpcEndpointStatusApplyConfiguration {
	return &VpcEndpointStatusApplyConfiguration{}
}

// WithLocalVIP sets the LocalVIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalVIP field is set to the value of the last call.
func (b *VpcEndpointStatusApplyConfiguration) WithLocalVIP(value string) *VpcEndpointStatusApplyConfiguration {
	b.LocalVIP = &value
	return b
}

// WithTransitVIP sets the TransitVIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TransitVIP field is set to the value of the last call.
func (b *VpcEndpointStatusApplyConfiguration) WithTransitVIP(value string) *VpcEndpointStatusApplyConfiguration {
	b.TransitVIP = &value
	return b
}

// WithSnatIP sets the SnatIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnatIP field is set to the value of the last call.
func (b *VpcEndpointStatusApplyConfiguration) WithSnatIP(value string) *VpcEndpointStatusApplyConfiguration {
	b.SnatIP = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *VpcEndpointStatusApplyConfiguration) WithReady(value bool) *VpcEndpointStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *VpcEndpointStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *VpcEndpointStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
