/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// VpcNatGatewaySpecApplyConfiguration represents a declarative configuration of the VpcNatGatewaySpec type for use
// with apply.
type VpcNatGatewaySpecApplyConfiguration struct {
	Vpc             *string                          `json:"vpc,omitempty"`
	Subnet          *string                          `json:"subnet,omitempty"`
	ExternalSubnets []string                         `json:"externalSubnets,omitempty"`
	LanIP           *string                          `json:"lanIp,omitempty"`
	Selector        []string                         `json:"selector,omitempty"`
	Tolerations     []corev1.Toleration              `json:"tolerations,omitempty"`
	Affinity        *corev1.Affinity                 `json:"affinity,omitempty"`
	QoSPolicy       *string                          `json:"qosPolicy,omitempty"`
	BgpSpeaker      *VpcBgpSpeakerApplyConfiguration `json:"bgpSpeaker,omitempty"`
	Routes          []RouteApplyConfiguration        `json:"routes,omitempty"`
	NoDefaultEIP    *bool                            `json:"noDefaultEIP,omitempty"`
}

// VpcNatGatewaySpecApplyConfiguration constructs a declarative configuration of the VpcNatGatewaySpec type for use with
// apply.
func VpcNatGatewaySpec() *VpcNatGatewaySpecApplyConfiguration {
	return &VpcNatGatewaySpecApplyConfiguration{}
}

// WithVpc sets the Vpc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vpc field is set to the value of the last call.
func (b *VpcNatGatewaySpecApplyConfiguration) WithVpc(value string) *VpcNatGatewaySpecApplyConfiguration {
	b.Vpc = &value
	return b
}

// WithSubnet sets the Subnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subnet field is set to the value of the last call.
func (b *VpcNatGatewaySpecApplyConfiguration) WithSubnet(value string) *VpcNatGatewaySpecApplyConfiguration {
	b.Subnet = &value
	return b
}

// WithExternalSubnets adds the given value to the ExternalSubnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExternalSubnets field.
func (b *VpcNatGatewaySpecApplyConfiguration) WithExternalSubnets(values ...string) *VpcNatGatewaySpecApplyConfiguration {
	for i := range values {
		b.ExternalSubnets = append(b.ExternalSubnets, values[i])
	}
	return b
}

// WithLanIP sets the LanIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LanIP field is set to the value of the last call.
func (b *VpcNatGatewaySpecApplyConfiguration) WithLanIP(value string) *VpcNatGatewaySpecApplyConfiguration {
	b.LanIP = &value
	return b
}

// WithSelector adds the given value to the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Selector field.
func (b *VpcNatGatewaySpecApplyConfiguration) WithSelector(values ...string) *VpcNatGatewaySpecApplyConfiguration {
	for i := range values {
		b.Selector = append(b.Selector, values[i])
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *VpcNatGatewaySpecApplyConfiguration) WithTolerations(values ...corev1.Toleration) *VpcNatGatewaySpecApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *VpcNatGatewaySpecApplyConfiguration) WithAffinity(value corev1.Affinity) *VpcNatGatewaySpecApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithQoSPolicy sets the QoSPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QoSPolicy field is set to the value of the last call.
func (b *VpcNatGatewaySpecApplyConfiguration) WithQoSPolicy(value string) *VpcNatGatewaySpecApplyConfiguration {
	b.QoSPolicy = &value
	return b
}

// WithBgpSpeaker sets the BgpSpeaker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BgpSpeaker field is set to the value of the last call.
func (b *VpcNatGatewaySpecApplyConfiguration) WithBgpSpeaker(value *VpcBgpSpeakerApplyConfiguration) *VpcNatGatewaySpecApplyConfiguration {
	b.BgpSpeaker = value
	return b
}

// WithRoutes adds the given value to the Routes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Routes field.
func (b *VpcNatGatewaySpecApplyConfiguration) WithRoutes(values ...*RouteApplyConfiguration) *VpcNatGatewaySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoutes")
		}
		b.Routes = append(b.Routes, *values[i])
	}
	return b
}

// WithNoDefaultEIP sets the NoDefaultEIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NoDefaultEIP field is set to the value of the last call.
func (b *VpcNatGatewaySpecApplyConfiguration) WithNoDefaultEIP(value bool) *VpcNatGatewaySpecApplyConfiguration {
	b.NoDefaultEIP = &value
	return b
}
