/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VpcWireGuardPeerStatusApplyConfiguration represents a declarative configuration of the VpcWireGuardPeerStatus type for use
// with apply.
type VpcWireGuardPeerStatusApplyConfiguration struct {
	// Ready state of the peer.
	Ready *bool `json:"ready,omitempty"`
	// Allocated or requested client tunnel IP.
	ClientIP *string `json:"clientIP,omitempty"`
	// Client public key actually programmed on the server.
	PublicKey *string `json:"publicKey,omitempty"`
	// Server public key copied from the gateway.
	ServerPublicKey *string `json:"serverPublicKey,omitempty"`
	// Public endpoint copied from the gateway.
	Endpoint *string `json:"endpoint,omitempty"`
	// Secret containing wg-quick.conf when generateKey is true.
	ConfigSecret *string `json:"configSecret,omitempty"`
	// Conditions represent the latest state of the object.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// VpcWireGuardPeerStatusApplyConfiguration constructs a declarative configuration of the VpcWireGuardPeerStatus type for use with
// apply.
func VpcWireGuardPeerStatus() *VpcWireGuardPeerStatusApplyConfiguration {
	return &VpcWireGuardPeerStatusApplyConfiguration{}
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *VpcWireGuardPeerStatusApplyConfiguration) WithReady(value bool) *VpcWireGuardPeerStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithClientIP sets the ClientIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientIP field is set to the value of the last call.
func (b *VpcWireGuardPeerStatusApplyConfiguration) WithClientIP(value string) *VpcWireGuardPeerStatusApplyConfiguration {
	b.ClientIP = &value
	return b
}

// WithPublicKey sets the PublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicKey field is set to the value of the last call.
func (b *VpcWireGuardPeerStatusApplyConfiguration) WithPublicKey(value string) *VpcWireGuardPeerStatusApplyConfiguration {
	b.PublicKey = &value
	return b
}

// WithServerPublicKey sets the ServerPublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerPublicKey field is set to the value of the last call.
func (b *VpcWireGuardPeerStatusApplyConfiguration) WithServerPublicKey(value string) *VpcWireGuardPeerStatusApplyConfiguration {
	b.ServerPublicKey = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *VpcWireGuardPeerStatusApplyConfiguration) WithEndpoint(value string) *VpcWireGuardPeerStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithConfigSecret sets the ConfigSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigSecret field is set to the value of the last call.
func (b *VpcWireGuardPeerStatusApplyConfiguration) WithConfigSecret(value string) *VpcWireGuardPeerStatusApplyConfiguration {
	b.ConfigSecret = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *VpcWireGuardPeerStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *VpcWireGuardPeerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
