/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VpcWireGuardStatusApplyConfiguration represents a declarative configuration of the VpcWireGuardStatus type for use
// with apply.
type VpcWireGuardStatusApplyConfiguration struct {
	// Ready state of the WireGuard server.
	Ready *bool `json:"ready,omitempty"`
	// LAN IP of the server pod.
	LanIP *string `json:"lanIp,omitempty"`
	// Public endpoint host:port clients should use.
	Endpoint *string `json:"endpoint,omitempty"`
	// Server public key.
	PublicKey *string `json:"publicKey,omitempty"`
	// Client CIDR from clientSubnet.
	ClientCIDR *string `json:"clientCIDR,omitempty"`
	// Tunnel address assigned to wg0 from clientSubnet.
	ServerTunnelIP *string `json:"serverTunnelIP,omitempty"`
	// Secret storing the generated server private key.
	ServerKeySecret *string `json:"serverKeySecret,omitempty"`
	// Conditions represent the latest state of the object.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// VpcWireGuardStatusApplyConfiguration constructs a declarative configuration of the VpcWireGuardStatus type for use with
// apply.
func VpcWireGuardStatus() *VpcWireGuardStatusApplyConfiguration {
	return &VpcWireGuardStatusApplyConfiguration{}
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *VpcWireGuardStatusApplyConfiguration) WithReady(value bool) *VpcWireGuardStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithLanIP sets the LanIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LanIP field is set to the value of the last call.
func (b *VpcWireGuardStatusApplyConfiguration) WithLanIP(value string) *VpcWireGuardStatusApplyConfiguration {
	b.LanIP = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *VpcWireGuardStatusApplyConfiguration) WithEndpoint(value string) *VpcWireGuardStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithPublicKey sets the PublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicKey field is set to the value of the last call.
func (b *VpcWireGuardStatusApplyConfiguration) WithPublicKey(value string) *VpcWireGuardStatusApplyConfiguration {
	b.PublicKey = &value
	return b
}

// WithClientCIDR sets the ClientCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCIDR field is set to the value of the last call.
func (b *VpcWireGuardStatusApplyConfiguration) WithClientCIDR(value string) *VpcWireGuardStatusApplyConfiguration {
	b.ClientCIDR = &value
	return b
}

// WithServerTunnelIP sets the ServerTunnelIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerTunnelIP field is set to the value of the last call.
func (b *VpcWireGuardStatusApplyConfiguration) WithServerTunnelIP(value string) *VpcWireGuardStatusApplyConfiguration {
	b.ServerTunnelIP = &value
	return b
}

// WithServerKeySecret sets the ServerKeySecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerKeySecret field is set to the value of the last call.
func (b *VpcWireGuardStatusApplyConfiguration) WithServerKeySecret(value string) *VpcWireGuardStatusApplyConfiguration {
	b.ServerKeySecret = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *VpcWireGuardStatusApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *VpcWireGuardStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
