/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// VpcWireGuardSpecApplyConfiguration represents a declarative configuration of the VpcWireGuardSpec type for use
// with apply.
type VpcWireGuardSpecApplyConfiguration struct {
	// Namespace where the WireGuard StatefulSet/Pod will be created.
	// If empty, defaults to the kube-ovn controller namespace.
	Namespace *string `json:"namespace,omitempty"`
	// VPC name. Immutable after creation.
	Vpc *string `json:"vpc,omitempty"`
	// Overlay subnet for the WireGuard server pod LAN NIC. Immutable after creation.
	Subnet *string `json:"subnet,omitempty"`
	// Optional static LAN IP on spec.subnet.
	LanIP *string `json:"lanIp,omitempty"`
	// Overlay subnet used as the client IP pool. Immutable after creation.
	ClientSubnet *string `json:"clientSubnet,omitempty"`
	// UDP listen port. Defaults to 51820.
	ListenPort *int32 `json:"listenPort,omitempty"`
	// Optional WireGuard interface MTU.
	MTU *int32 `json:"mtu,omitempty"`
	// How the server is reached from the internet.
	Exposure *VpcWireGuardExposureApplyConfiguration `json:"exposure,omitempty"`
	// Generate a server keypair into a Secret. Mutually exclusive with publicKey.
	GenerateServerKey *bool `json:"generateServerKey,omitempty"`
	// Existing server public key when generateServerKey is false.
	PublicKey *string `json:"publicKey,omitempty"`
	// Secret holding the existing server private key when generateServerKey is false.
	PrivateKeySecretRef *corev1.SecretKeySelector `json:"privateKeySecretRef,omitempty"`
	// CIDRs advertised to clients as AllowedIPs. Empty means all CIDRs of the VPC.
	AllowedIPs []string `json:"allowedIPs,omitempty"`
	// Pod selector for the WireGuard server.
	Selector []string `json:"selector,omitempty"`
	// Pod tolerations.
	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`
	// Pod affinity.
	Affinity *corev1.Affinity `json:"affinity,omitempty"`
}

// VpcWireGuardSpecApplyConfiguration constructs a declarative configuration of the VpcWireGuardSpec type for use with
// apply.
func VpcWireGuardSpec() *VpcWireGuardSpecApplyConfiguration {
	return &VpcWireGuardSpecApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithNamespace(value string) *VpcWireGuardSpecApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithVpc sets the Vpc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vpc field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithVpc(value string) *VpcWireGuardSpecApplyConfiguration {
	b.Vpc = &value
	return b
}

// WithSubnet sets the Subnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subnet field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithSubnet(value string) *VpcWireGuardSpecApplyConfiguration {
	b.Subnet = &value
	return b
}

// WithLanIP sets the LanIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LanIP field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithLanIP(value string) *VpcWireGuardSpecApplyConfiguration {
	b.LanIP = &value
	return b
}

// WithClientSubnet sets the ClientSubnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSubnet field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithClientSubnet(value string) *VpcWireGuardSpecApplyConfiguration {
	b.ClientSubnet = &value
	return b
}

// WithListenPort sets the ListenPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ListenPort field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithListenPort(value int32) *VpcWireGuardSpecApplyConfiguration {
	b.ListenPort = &value
	return b
}

// WithMTU sets the MTU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MTU field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithMTU(value int32) *VpcWireGuardSpecApplyConfiguration {
	b.MTU = &value
	return b
}

// WithExposure sets the Exposure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exposure field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithExposure(value *VpcWireGuardExposureApplyConfiguration) *VpcWireGuardSpecApplyConfiguration {
	b.Exposure = value
	return b
}

// WithGenerateServerKey sets the GenerateServerKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateServerKey field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithGenerateServerKey(value bool) *VpcWireGuardSpecApplyConfiguration {
	b.GenerateServerKey = &value
	return b
}

// WithPublicKey sets the PublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicKey field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithPublicKey(value string) *VpcWireGuardSpecApplyConfiguration {
	b.PublicKey = &value
	return b
}

// WithPrivateKeySecretRef sets the PrivateKeySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeySecretRef field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithPrivateKeySecretRef(value corev1.SecretKeySelector) *VpcWireGuardSpecApplyConfiguration {
	b.PrivateKeySecretRef = &value
	return b
}

// WithAllowedIPs adds the given value to the AllowedIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedIPs field.
func (b *VpcWireGuardSpecApplyConfiguration) WithAllowedIPs(values ...string) *VpcWireGuardSpecApplyConfiguration {
	for i := range values {
		b.AllowedIPs = append(b.AllowedIPs, values[i])
	}
	return b
}

// WithSelector adds the given value to the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Selector field.
func (b *VpcWireGuardSpecApplyConfiguration) WithSelector(values ...string) *VpcWireGuardSpecApplyConfiguration {
	for i := range values {
		b.Selector = append(b.Selector, values[i])
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *VpcWireGuardSpecApplyConfiguration) WithTolerations(values ...corev1.Toleration) *VpcWireGuardSpecApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *VpcWireGuardSpecApplyConfiguration) WithAffinity(value corev1.Affinity) *VpcWireGuardSpecApplyConfiguration {
	b.Affinity = &value
	return b
}
