/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// IPListerExpansion allows custom methods to be added to
// IPLister.
type IPListerExpansion interface{}

// IptablesDnatRuleListerExpansion allows custom methods to be added to
// IptablesDnatRuleLister.
type IptablesDnatRuleListerExpansion interface{}

// IptablesEIPListerExpansion allows custom methods to be added to
// IptablesEIPLister.
type IptablesEIPListerExpansion interface{}

// IptablesFIPRuleListerExpansion allows custom methods to be added to
// IptablesFIPRuleLister.
type IptablesFIPRuleListerExpansion interface{}

// IptablesSnatRuleListerExpansion allows custom methods to be added to
// IptablesSnatRuleLister.
type IptablesSnatRuleListerExpansion interface{}

// OvnDnatRuleListerExpansion allows custom methods to be added to
// OvnDnatRuleLister.
type OvnDnatRuleListerExpansion interface{}

// OvnEipListerExpansion allows custom methods to be added to
// OvnEipLister.
type OvnEipListerExpansion interface{}

// OvnFipListerExpansion allows custom methods to be added to
// OvnFipLister.
type OvnFipListerExpansion interface{}

// OvnSnatRuleListerExpansion allows custom methods to be added to
// OvnSnatRuleLister.
type OvnSnatRuleListerExpansion interface{}

// ProviderNetworkListerExpansion allows custom methods to be added to
// ProviderNetworkLister.
type ProviderNetworkListerExpansion interface{}

// QoSPolicyListerExpansion allows custom methods to be added to
// QoSPolicyLister.
type QoSPolicyListerExpansion interface{}

// SecurityGroupListerExpansion allows custom methods to be added to
// SecurityGroupLister.
type SecurityGroupListerExpansion interface{}

// SubnetListerExpansion allows custom methods to be added to
// SubnetLister.
type SubnetListerExpansion interface{}

// SwitchLBRuleListerExpansion allows custom methods to be added to
// SwitchLBRuleLister.
type SwitchLBRuleListerExpansion interface{}

// VipListerExpansion allows custom methods to be added to
// VipLister.
type VipListerExpansion interface{}

// VlanListerExpansion allows custom methods to be added to
// VlanLister.
type VlanListerExpansion interface{}

// VpcListerExpansion allows custom methods to be added to
// VpcLister.
type VpcListerExpansion interface{}

// VpcDnsListerExpansion allows custom methods to be added to
// VpcDnsLister.
type VpcDnsListerExpansion interface{}

// VpcNatGatewayListerExpansion allows custom methods to be added to
// VpcNatGatewayLister.
type VpcNatGatewayListerExpansion interface{}
