/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GobgpConfigLister helps list GobgpConfigs.
// All objects returned here must be treated as read-only.
type GobgpConfigLister interface {
	// List lists all GobgpConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.GobgpConfig, err error)
	// GobgpConfigs returns an object that can list and get GobgpConfigs.
	GobgpConfigs(namespace string) GobgpConfigNamespaceLister
	GobgpConfigListerExpansion
}

// gobgpConfigLister implements the gobgpConfigLister interface.
type gobgpConfigLister struct {
	listers.ResourceIndexer[*kubeovnv1.GobgpConfig]
}

// NewGobgpConfigLister returns a new gobgpConfigLister.
func NewGobgpConfigLister(indexer cache.Indexer) GobgpConfigLister {
	return &gobgpConfigLister{listers.New[*kubeovnv1.GobgpConfig](indexer, kubeovnv1.Resource("gobgpconfig"))}
}

// gobgpConfigs returns an object that can list and get gobgpConfigs.
func (s *gobgpConfigLister) GobgpConfigs(namespace string) GobgpConfigNamespaceLister {
	return gobgpConfigNamespaceLister{listers.NewNamespaced[*kubeovnv1.GobgpConfig](s.ResourceIndexer, namespace)}
}

// gobgpConfigNamespaceLister helps list and get gobgpConfigs.
// All objects returned here must be treated as read-only.
type GobgpConfigNamespaceLister interface {
	// List lists all gobgpConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.GobgpConfig, err error)
	// Get retrieves the GobgpConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.GobgpConfig, error)
	GobgpConfigNamespaceListerExpansion
}

// gobgpConfigNamespaceLister implements the gobgpConfigNamespaceLister
// interface.
type gobgpConfigNamespaceLister struct {
	listers.ResourceIndexer[*kubeovnv1.GobgpConfig]
}
