/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OvnEipLister helps list OvnEips.
// All objects returned here must be treated as read-only.
type OvnEipLister interface {
	// List lists all OvnEips in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.OvnEip, err error)
	// Get retrieves the OvnEip from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.OvnEip, error)
	OvnEipListerExpansion
}

// ovnEipLister implements the OvnEipLister interface.
type ovnEipLister struct {
	listers.ResourceIndexer[*kubeovnv1.OvnEip]
}

// NewOvnEipLister returns a new OvnEipLister.
func NewOvnEipLister(indexer cache.Indexer) OvnEipLister {
	return &ovnEipLister{listers.New[*kubeovnv1.OvnEip](indexer, kubeovnv1.Resource("ovneip"))}
}
