/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubeovnv1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VpcWireGuardLister helps list VpcWireGuards.
// All objects returned here must be treated as read-only.
type VpcWireGuardLister interface {
	// List lists all VpcWireGuards in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubeovnv1.VpcWireGuard, err error)
	// Get retrieves the VpcWireGuard from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubeovnv1.VpcWireGuard, error)
	VpcWireGuardListerExpansion
}

// vpcWireGuardLister implements the VpcWireGuardLister interface.
type vpcWireGuardLister struct {
	listers.ResourceIndexer[*kubeovnv1.VpcWireGuard]
}

// NewVpcWireGuardLister returns a new VpcWireGuardLister.
func NewVpcWireGuardLister(indexer cache.Indexer) VpcWireGuardLister {
	return &vpcWireGuardLister{listers.New[*kubeovnv1.VpcWireGuard](indexer, kubeovnv1.Resource("vpcwireguard"))}
}
