{{- $natRoleName := include "kubeovn.resourceName" (dict "context" . "suffix" "system-vpc-nat-gw") -}}
{{- $natBindingName := include "kubeovn.resourceName" (dict "context" . "suffix" "vpc-nat-gw") -}}
{{- $natServiceAccountName := include "kubeovn.resourceName" (dict "context" . "suffix" "vpc-nat-gw") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: {{ $natRoleName }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - watch
  - apiGroups:
      - kubeovn.io
    resources:
      - iptables-eips
      - subnets
      - vpc-nat-gateways
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: {{ $natBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $natRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ $natServiceAccountName }}
    namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $natServiceAccountName }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
