---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-ovn-controller-secrets
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create]
  - apiGroups: [""]
    resources: [secrets]
    resourceNames: [kube-ovn-tls, ovn-ipsec-ca, ovn-ipsec-signer]
    verbs: [get, update]
{{- if .Values.ipsec.certManager.enabled }}
  - apiGroups: [cert-manager.io]
    resources: [certificaterequests]
    verbs: [get, list, watch, create]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-ovn-controller-secrets
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-ovn-controller-secrets
subjects:
  - kind: ServiceAccount
    name: ovn
    namespace: {{ .Values.namespace }}
