{{- $ovnServiceAccountName := include "kubeovn.ovnServiceAccountName" . -}}
{{- $ovsServiceAccountName := include "kubeovn.ovsServiceAccountName" . -}}
{{- $appServiceAccountName := include "kubeovn.appServiceAccountName" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $ovnServiceAccountName }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
{{-  if .Values.global.registry.imagePullSecrets }}
imagePullSecrets:
{{- range $index, $secret := .Values.global.registry.imagePullSecrets }}
{{- if $secret }}
- name: {{ $secret | quote}}
{{- end }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $ovsServiceAccountName }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
{{-  if .Values.global.registry.imagePullSecrets }}
imagePullSecrets:
{{- range $index, $secret := .Values.global.registry.imagePullSecrets }}
{{- if $secret }}
  - name: {{ $secret | quote}}
{{- end }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $appServiceAccountName }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
{{-  if .Values.global.registry.imagePullSecrets }}
imagePullSecrets:
{{- range $index, $secret := .Values.global.registry.imagePullSecrets }}
{{- if $secret }}
  - name: {{ $secret | quote}}
{{- end }}
{{- end }}
{{- end }}
