{{- if include "kubeovn.renderControlPlane" . }}
{{- $svc := index .Values "ovn-central" "service" }}
{{- include "kubeovn.validateService" . }}
kind: Service
apiVersion: v1
metadata:
  name: ovn-sb
  namespace: {{ .Values.namespace }}
  {{- if and (eq $svc.type "LoadBalancer") $svc.loadBalancerIP }}
  annotations:
    metallb.universe.tf/allow-shared-ip: kube-ovn-central
  {{- end }}
spec:
  ports:
    - name: ovn-sb
      protocol: TCP
      port: 6642
      targetPort: 6642
  type: {{ $svc.type | default "ClusterIP" }}
  {{- if and (eq $svc.type "LoadBalancer") $svc.loadBalancerIP }}
  loadBalancerIP: {{ $svc.loadBalancerIP | quote }}
  {{- end }}
  {{- if and (or (eq $svc.type "LoadBalancer") (eq $svc.type "NodePort")) $svc.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $svc.externalTrafficPolicy }}
  {{- end }}
  {{- if eq .Values.networking.NET_STACK "dual_stack" }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  selector:
    app: ovn-central
    {{- if ne .Values.OVN_CENTRAL_MODE "single" }}
    ovn-sb-leader: "true"
    {{- end }}
  sessionAffinity: None

{{- end }}
