{{- if include "kubeovn.renderControlPlane" . }}
{{- $svc := index .Values "ovn-central" "service" }}
{{- $hcp := index .Values "ovn-central" "hcp" }}
{{- $hcpSvc := index .Values "ovn-central" "hcp" "service" }}
{{- if not $hcp.enabled }}
{{- include "kubeovn.validateService" . }}
{{- end }}
kind: Service
apiVersion: v1
metadata:
  name: ovn-sb
  namespace: {{ include "kubeovn.centralNamespace" . }}
  {{- if and (not $hcp.enabled) (eq $svc.type "LoadBalancer") $svc.loadBalancerIP }}
  annotations:
    metallb.universe.tf/allow-shared-ip: kube-ovn-central
  {{- end }}
spec:
  ports:
    - name: ovn-sb
      protocol: TCP
      port: 6642
      targetPort: 6642
      {{- if and $hcp.enabled (or (eq $hcpSvc.type "NodePort") (eq $hcpSvc.type "LoadBalancer")) }}
      nodePort: {{ $hcpSvc.sbNodePort }}
      {{- end }}
  type: {{ ternary ($hcpSvc.type | default "ClusterIP") ($svc.type | default "ClusterIP") $hcp.enabled }}
  {{- if and (not $hcp.enabled) (eq $svc.type "LoadBalancer") $svc.loadBalancerIP }}
  loadBalancerIP: {{ $svc.loadBalancerIP | quote }}
  {{- end }}
  {{- if and (not $hcp.enabled) (or (eq $svc.type "LoadBalancer") (eq $svc.type "NodePort")) $svc.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $svc.externalTrafficPolicy }}
  {{- end }}
  {{- if eq .Values.networking.NET_STACK "dual_stack" }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  selector:
    app: ovn-central
    {{- if or $hcp.enabled (ne .Values.OVN_CENTRAL_MODE "single") }}
    ovn-sb-leader: "true"
    {{- end }}
  sessionAffinity: None

{{- end }}
