{{- if .Values.agent.serviceMonitor.enabled }}
{{- $agentName := include "kubeovn.agentName" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $agentName }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ $agentName }}
    app.kubernetes.io/part-of: kube-ovn
    {{- with .Values.agent.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 15s
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $agentName }}
{{- end }}
