{{- $agentName := include "kubeovn.agentName" . -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $agentName }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ $agentName }}
    app.kubernetes.io/part-of: kube-ovn
    {{- with .Values.agent.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $agentName }}
    app.kubernetes.io/part-of: kube-ovn
  ports:
    - port: {{ .Values.agent.metrics.port }}
      name: metrics
  {{- if eq .Values.networking.stack "Dual" }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
