kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-ipsec-config
  namespace: {{ .Values.namespace }}
data:
  image: {{ .Values.ipsecGw.image.repository }}:{{ .Values.ipsecGw.image.tag }}
  {{- with .Values.ipsecGw.namePrefix }}
  ipsecGwNamePrefix: {{ . | quote }}
  {{- end }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-ipsec-gw-config
  namespace: {{ .Values.namespace }}
data:
  enable-vpc-ipsec-gw: "{{ .Values.features.enableIpsecGateways }}"
