apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ips.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: ips
    singular: ip
    kind: IP
    shortNames:
      - ip
  additionalPrinterColumns:
    - name: IP
      type: string
      JSONPath: .spec.ipAddress
    - name: Mac
      type: string
      JSONPath: .spec.macAddress
    - name: Node
      type: string
      JSONPath: .spec.nodeName
    - name: Subnet
      type: string
      JSONPath: .spec.subnet
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            podName:
              type: string
            namespace:
              type: string
            subnet:
              type: string
            attachSubnets:
              type: array
              items:
                type: string
            nodeName:
              type: string
            ipAddress:
              type: string
            attachIps:
              type: array
              items:
                type: string
            macAddress:
              type: string
            attachMacs:
              type: array
              items:
                type: string
            containerID:
              type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subnets.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: subnets
    singular: subnet
    kind: Subnet
    shortNames:
      - subnet
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Provider
      type: string
      JSONPath: .spec.provider
    - name: Protocol
      type: string
      JSONPath: .spec.protocol
    - name: CIDR
      type: string
      JSONPath: .spec.cidrBlock
    - name: Private
      type: boolean
      JSONPath: .spec.private
    - name: NAT
      type: boolean
      JSONPath: .spec.natOutgoing
    - name: Default
      type: boolean
      JSONPath: .spec.default
    - name: GatewayType
      type: string
      JSONPath: .spec.gatewayType
    - name: Used
      type: number
      JSONPath: .status.usingIPs
    - name: Available
      type: number
      JSONPath: .status.availableIPs
  validation:
    openAPIV3Schema:
      properties:
        status:
          type: object
          properties:
            availableIPs:
              type: number
            usingIPs:
              type: number
            activateGateway:
              type: string
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
                  lastUpdateTime:
                    type: string
                  lastTransitionTime:
                    type: string
        spec:
          type: object
          properties:
            default:
              type: boolean
            protocol:
              type: string
            cidrBlock:
              type: string
            namespaces:
              type: array
              items:
                type: string
            gateway:
              type: string
            provider:
              type: string
            excludeIps:
              type: array
              items:
                type: string
            gatewayType:
              type: string
            allowSubnets:
              type: array
              items:
                type: string
            gatewayNode:
              type: string
            natOutgoing:
              type: boolean
            private:
              type: boolean
            vlan:
              type: string
            underlayGateway:
              type: boolean
            disableInterConnection:
              type: boolean
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vlans.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: vlans
    singular: vlan
    kind: Vlan
    shortNames:
      - vlan
  additionalPrinterColumns:
    - name: VlanID
      type: string
      JSONPath: .spec.vlanId
    - name: ProviderInterfaceName
      type: string
      JSONPath: .spec.providerInterfaceName
    - name: Subnet
      type: string
      JSONPath: .spec.subnet
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            vlanId:
              type: integer
            providerInterfaceName:
              type: string
            logicalInterfaceName:
              type: string
            subnet:
              type: string
