---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kube-ovn
spec:
  ca:
    secretName: kube-ovn-ca
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-ovn-ca
  namespace: cert-manager
type: Opaque
data:
  tls.crt: "KUBE_OVN_CA_CERT"
  tls.key: "KUBE_OVN_CA_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: ovn-ipsec-ca
  namespace: kube-system
type: Opaque
data:
  cacert: "KUBE_OVN_CA_CERT"
