apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  type: "centralized"
  external-gw-nodes: "kube-ovn-worker"  # NodeName in kubernetes which will act the overlay to underlay gateway functions
  external-gw-nic: "eth1"               # The nic that will be bridged into ovs and act as overlay to underlay gateway
  external-gw-addr: "172.56.0.1/16"     # The ip and mask of the underlay physical gateway
  nic-ip: "172.56.0.100/16"             # The ip and mask of the underlay physical network for logical route external gw port
  nic-mac: "16:52:f3:13:6a:25"          # The mac of the underlay physical gateway
