name: Build Win64
on: workflow_dispatch

jobs:
  build-ovs-and-ovn:
    name: Build OVS and OVN
    runs-on: windows-2019
    steps:
      - name: Check out PTHREADS4W
        run: |
          mkdir pthreads4w
          git clone https://git.code.sf.net/p/pthreads4w/code pthreads4w\code

      - name: Check out OVS
        uses: actions/checkout@v2
        with:
          repository: openvswitch/ovs
          ref: v2.17.0
          path: ovs

      - name: Check out OVN
        uses: actions/checkout@v2
        with:
          repository: ovn-org/ovn
          ref: branch-22.03
          path: ovn

      - name: Apply OVS patches
        working-directory: ovs
        run: |
          # fix kernel crash
          Invoke-WebRequest -Uri "https://github.com/kubeovn/ovs/commit/4ffb7de197dd578d3c6d3e0bf045e4451113a216.patch" -OutFile ..\ovs-01.patch
          # support for building in github actions
          Invoke-WebRequest -Uri "https://github.com/kubeovn/ovs/commit/fafb5d6d2140e2778f681f6ff0e9f4cc3c0a9e37.patch" -OutFile ..\ovs-02.patch
          # listen on tcp 127.0.0.1:6643 by default
          Invoke-WebRequest -Uri "https://github.com/kubeovn/ovs/commit/f806e839b76e82308a6db4e8054fb0acbe3d2ad0.patch" -OutFile ..\ovs-03.patch
          git apply ..\ovs-01.patch
          git apply ..\ovs-02.patch
          git apply ..\ovs-03.patch

      - name: Apply OVN patches
        working-directory: ovn
        run: |
          # add support for windows
          Invoke-WebRequest -Uri "https://github.com/kubeovn/ovn/commit/b7d91200f20e1ae5083c247fc966d196ecee2f91.patch" -OutFile ..\ovn-01.patch
          git apply ..\ovn-01.patch

      - name: Build PTHREADS4W
        working-directory: pthreads4w\code
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake all install

      - name: Install pypiwin32
        run: python3 -m pip install pypiwin32

      - name: Build OVS and OVN
        shell: cmd
        env:
          MSYS2_PATH_TYPE: inherit
        run: |
          SETLOCAL ENABLEDELAYEDEXPANSION
          SET _p4w_dir=%CD:\=/%/pthreads4w/PTHREADS-BUILT
          FOR /F "tokens=* USEBACKQ" %%F IN (`C:\msys64\usr\bin\cygpath.exe -u "%CD%\ovs"`) DO (
            SET _ovs_dir=%%F
          )
          FOR /F "tokens=* USEBACKQ" %%F IN (`C:\msys64\usr\bin\cygpath.exe -u "%CD%\ovn"`) DO (
            SET _ovn_dir=%%F
          )
          CALL "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          SET _vs_path=
          FOR %%d IN ("%PATH:;=";"%") DO (
            echo %%~d | findstr /C:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" > nul && set _vs_path=!_vs_path!;%%~d
          )
          SET PATH="%_vs_path%;%PATH%"
          C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
          C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm libtool autoconf automake-wrapper"
          C:\msys64\usr\bin\bash.exe -lc "rm -f `which link`"
          C:\msys64\usr\bin\bash.exe -lc "cd '%_ovs_dir%' && ./boot.sh"
          C:\msys64\usr\bin\bash.exe -lc "cd '%_ovs_dir%' && ./configure CC=./build-aux/cccl LD='`which link`' LIBS='-lws2_32 -lShlwapi -liphlpapi -lwbemuuid -lole32 -loleaut32' --prefix='C:/openvswitch/usr' --localstatedir='C:/openvswitch/var' --sysconfdir='C:/openvswitch/etc' --with-pthread='%_p4w_dir%' --disable-ssl"
          C:\msys64\usr\bin\bash.exe -lc "cd '%_ovs_dir%' && make -j"
          C:\msys64\usr\bin\bash.exe -lc "cd '%_ovs_dir%' && make windows_installer"
          C:\msys64\usr\bin\bash.exe -lc "cd '%_ovn_dir%' && ./boot.sh"
          C:\msys64\usr\bin\bash.exe -lc "cd '%_ovn_dir%' && ./configure CC=./build-aux/cccl LD='`which link`' LIBS='-lws2_32 -lShlwapi -liphlpapi -lwbemuuid -lole32 -loleaut32' --prefix='C:/ovn/usr' --localstatedir='C:/ovn/var' --sysconfdir='C:/ovn/etc' --with-pthread='%_p4w_dir%' --disable-ssl --with-ovs-source='../ovs' --with-ovs-build='../ovs'"
          C:\msys64\usr\bin\bash.exe -lc "cd '%_ovn_dir%' && make -j"
          C:\msys64\usr\bin\bash.exe -lc "cd '%_ovn_dir%' && make install"

      - name: Upload OVS
        uses: actions/upload-artifact@v2
        with:
          name: ovs
          path: ovs\windows\ovs-windows-installer\bin\x64\Release\OpenvSwitch.msi

      - name: Upload OVN
        uses: actions/upload-artifact@v2
        with:
          name: ovn
          path: C:\ovn
