name: Build Base DPDK
on:
  workflow_dispatch:
  schedule:
    - cron: "20 19 * * *"

jobs:
  build-amd64:
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - release-1.12
    name: Build AMD64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build
        run: |
          make base-amd64-dpdk
          make base-tar-amd64-dpdk

      - name: Upload image to artifact
        uses: actions/upload-artifact@v3
        with:
          name: image-amd64-dpdk
          path: image-amd64-dpdk.tar

  push:
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - release-1.12
    needs:
      - build-amd64
    name: push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: image-amd64-dpdk

      - name: Load Image
        run: |
          docker load --input image-amd64-dpdk.tar

      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker images
          docker tag kubeovn/kube-ovn-base:$TAG-amd64-dpdk kubeovn/kube-ovn-base:$TAG-dpdk
          docker push kubeovn/kube-ovn-base:$TAG-dpdk
