name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - master
      - release-*
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: oilbeater/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: gpt-3.5-turbo
          top_p: 1
          temperature: 0.1