name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issues go stale after 60d of inactivity. Please comment or re-open the issue if you are still interested in getting this issue fixed.'
        stale-pr-message: 'PRs go stale after 60d of inactivity. Please comment or re-open the PR if you are still working on this PR.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 60
        exempt-issue-labels: 'ignore-no-issue-activity'